export const START_SIGNUP = 'START_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const START_SIGNIN = 'START_SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const AUTHENTICATE = 'AUTHENTICATE';

export const SIGNOUT = 'SIGNOUT';
